linebot/webhook.go
linebot/webhook_test.go

It has been described as 'X-Line-Signature' in the document.
And, API request uses it.

Update request header name.

---

examples/echo_bot/server.go
examples/echo_bot_handler/server.go
examples/kitchensink/server.go

ref. #20 
It is better to use `ListenAndServeTLS` method, but it is a just a sample code and should be simple. So I added comments about the actual use.

add comment to example codes

---

linebot/send_message_test.go
linebot/template.go

ref. #24 
added `omitempty` annotation to `ThumbnailImageURL` because `thumbnailImageURL` of `ButtonsTemplate` and `CarouselColumn` is optional.

make ThumbnailImageURL optional

---

linebot/send_message_test.go
linebot/template.go

NOTE: for backward compatibility (and not breaking any client library who use this SDK), I choose to use WithImageOptions() and return the object itself.
2017/11/30 New options for template message images:
"We have released imageAspectRatio, imageSize, and imageBackgroundColor
fields for Buttons and Carousel template messages. Using these fields,
you can configure the aspect ratio, size, and background color for
images used in template messages."
Ref:
- https://developers.line.me/en/docs/messaging-api/reference/#buttons
- https://developers.line.me/en/docs/messaging-api/reference/#carousel

Add WithImageOptions for buttons/carousel templates

---

linebot/imagemap.go
linebot/message.go
linebot/template.go

As discussed in #59 this would make the "marker" methods for the `ImagemapAction`, `Message`, `Template` and `TemplateAction` interfaces visible for consumers of this package, allowing them to implement them on their own (in case they just need to pass through data for example).

Make interface markers visible to other packages

---

linebot/account_link.go
linebot/account_link_test.go
linebot/client.go
linebot/response.go

https://developers.line.me/en/reference/messaging-api/#issue-link-token

Support issue link token api

---

linebot/flex.go

Thank you for the hard work for Line Bot SDK for Go 👍 
This PR changes
- Implement MarshalJSON for Flex Components, and Containers
- **Breaking** **Change** Remove field `Type` from Flex Components, and Containers
I think it very confusing to put the same `Type` to the named struct.

Implement MarshalJSON for Flex Components and Containers

---

linebot/event.go
linebot/webhook_test.go

Note: in the raw events of member join/leave, "left"/"leave" keys should
be avoid, since we can distinguish them via event type.

Add member join/leave event

---

linebot/event.go
linebot/webhook_test.go

Add new EventType for LINE Things, etc.

Add new EventType.

---

linebot/flex.go
linebot/flex_test.go
linebot/flex_unmarshal.go
linebot/send_message_test.go

#125 
when use UnmarshalFlexMessageJSON
when marshalJSON so size of SpacerComponent should be not empty string

omitempty size in SpacerComponent of flex message

---

linebot/event.go

1) `MarshalJSON` with a message type "file". `raw.Message` will be missing
2) `UnmarshalJSON` from the array of bytes from the previous operation
3) `runtime error: invalid memory address or nil pointer dereference` will be occurs

Fix: support marshalling message type "file"

---

examples/kitchensink/server.go
linebot/actions.go
linebot/flex_test.go

Resolve #143.
- Added `URIAction.AltURI` as optional property.
- Added tests to `flex_test.go` (because `altUri` property is supported only in Flex Messages).
- Update `kitchensink` server
- When the user says "flex json" command, the bot replies flex message with two buttons. When opened in the desktop version, the second link will open a different URI than the mobile version.

Add URIAction.AltURI.Desktop

---

README.md

What's changed:
- Title:
s/line-bot-sdk-go/LINE Messaging API SDK for Go/
- Added Introduction, Help and media, Versioning, Contributing sections
- Changed documentation links from reference to Messaging api overview
- Moved up Requirements section just before the Installation section
- Added Apache License boilerplate

Update README file as per template

---

linebot/client.go
linebot/get_quota.go
linebot/get_quota_test.go
linebot/response.go

- Gets the number of messages sent in the current month.
Refer https://developers.line.biz/en/reference/messaging-api/#get-consumption

Add support for message quota consumption.

---

.github/ISSUE_TEMPLATE/bug_report.md

GitHub is now supporting multiple issues with ISSUE_TEMPLATE **directory**.
I write a new issue template for bug report with commented old one, and put it into new ISSUE_TEMPLATE directory.
We can add some more types of issue templates, however first of all I start with bug report.

update issues template to apply multiple issues template

---

linebot/client.go
linebot/send_message.go
linebot/send_message_test.go

Sends push messages to multiple users at any time.
Refer https://developers.line.biz/en/reference/messaging-api/#send-broadcast-message

Support "Send broadcast api"

---

linebot/send_message.go
linebot/send_message_test.go

- add omitempty to `notificationDisabled` since it's optional

Add WithNotificationDisabled() to push/reply/multicast message API

---

linebot/client.go
linebot/oauth.go
linebot/oauth_test.go
linebot/response.go

https://developers.line.me/en/docs/messaging-api/reference/#issue-channel-access-token

Add `Issue channel access token` API

---

examples/delivery_helper/main.go
linebot/delivery.go
linebot/delivery_test.go

Add support for "Get number of sent broadcast messages"
https://developers.line.biz/en/reference/messaging-api/#get-number-of-broadcast-messages

Fix #156 no 6 Support get number of sent broadcast messages.

---

linebot/event.go
linebot/webhook_test.go

#160
Support [LINE Things scenario execution event](https://developers.line.biz/en/reference/messaging-api/#scenario-result-event)
* Add `Things.Result`
* Add `rawThingsResult`, `rawThingsActionResult`, `rawThingsEvent` for unmarshal `[]byte`
* Fix `Event.MarshalJSON()` and `Event.UnmarshalJSON()` to use `rawThings...` structs
* Add test cases for Marshaling and Unmarshaling Things Scenario Exuecution Result

support LINE Things scenario execution event

---

linebot/flex.go
linebot/flex_test.go

Add the missing property for configuring message bubble size for
flex message
[reference](https://developers.line.biz/en/reference/messaging-api/#bubble)

add bubble size property

---

linebot/flex.go

type FlexContainerType = string // alias type
Removed "=" in this declaration.
And "alias type" comment delete.
If this "=" is present, the linebot definition hover message will not be displayed in VSC on Mac OS.
Example
test.go code.
func testProc () {
var x linebot.TemplateAction
x.TemplateAction ()
_ = linebot.Client {}
_ = linebot.TextMessage {}
}
At this time, even if the mouse cursor is hovered over TemplateAction, Client, TextMessage, etc., the hint message is not displayed.
type FlexContainerType = string // alias type
This "=" is grammatical, but the VSC Go plugin doesn't seem to interpret correctly.

Fixed declaration of FlexContainerType

---

examples/insight_helper/main.go
linebot/client.go
linebot/insight.go
linebot/insight_test.go
linebot/response.go

fix #171 
Add support for https://developers.line.biz/en/news/#new-messaging-api-endpoints-for-friend-statistics-2019-07-08
Get number of message deliveries
Get number of followers
Get friend demographics

Support  07/08 Insight API.

---

examples/echo_bot/server.go
linebot/event.go
linebot/message.go
linebot/webhook_test.go

- New property added to "sticker message" webhook event
- example added in examples/echo_bot
Ref: https://developers.line.biz/en/reference/messaging-api/#wh-sticker

add field `stickerResourceType` to sicker message

---

linebot/insight.go
linebot/insight_test.go
linebot/response.go

- implements #177
- also add `apiNarrowcast` in message deliveries response
Ref: https://developers.line.biz/en/reference/messaging-api/#get-message-event

Add API to get user interaction statistics

---

linebot/flex.go
linebot/flex_test.go

[API reference](https://developers.line.biz/en/reference/messaging-api/#filler)

add flex property on filler component

---

linebot/client.go
linebot/progress.go
linebot/progress_test.go
linebot/response.go

- follow #190, #191, implements the following API:
https://developers.line.biz/en/reference/messaging-api/#get-narrowcast-progress-status
- use `ProgressType` for future use, i.e. we need to get other cast's progress.

Support "Get narrowcast message status API"

---

linebot/emoji.go
linebot/message.go
linebot/send_message_test.go

Fixed #199 
https://developers.line.biz/en/news/2020/04/14/messaging-api-update-april-2020/

Use LINE emoji in messages 

---

examples/access_token_helper/main.go
linebot/client.go
linebot/oauth2.go
linebot/oauth2_test.go
linebot/response.go

- implements #198
- real tested with examples/access_token_helper

Support "Channel access token v2.1"

---

linebot/emoji.go
linebot/send_message_test.go

Original the `index` of emoji is omitempty it means if `index=0` it will be omitted. But server could not accept any call without `index`.
- Add one more test index=0.
- Remove omit empty on Emoji index.

Fix emoji: Fix test error by remove "omit empty" on index

---

examples/access_token_helper/main.go
linebot/client.go
linebot/oauth2_test.go
linebot/response.go

Updates related to [get all valid channel access token key IDs v2.1 endpoint](https://developers.line.biz/en/reference/messaging-api/#get-all-valid-channel-access-token-key-ids-v2-1).
I updated [GetAccessTokensV2 method](https://github.com/line/line-bot-sdk-go/blob/master/linebot/oauth2.go#L64) because get all valid channel access tokens v2.1 endpoint seems already deprecated.
Close #214

Update channel access token v2.1 apis

---

linebot/client.go
linebot/send_message.go
linebot/send_message_test.go

Fixed #207  
API for Retry failed message 
Refer: https://developers.line.biz/en/reference/messaging-api/#retry-api-request

Add API for Retry failed message

---

CHANGELOG.md
linebot/version.go

Update version to v7.6.0 for 2020 May, August, and September updated.

Update version to v7.6.0

---

linebot/flex.go
linebot/flex_test.go

https://github.com/line/line-bot-sdk-go/issues/234
https://developers.line.biz/en/reference/messaging-api/#span
fix SpanComponent MarshalJSON type error

Support message api span component in flex message 2

---

linebot/client.go
linebot/webhook.go
linebot/webhook_test.go

Add API for[ set webhook endpointURL](https://developers.line.biz/en/reference/messaging-api/#set-webhook-endpoint-url)
Checklist #233

Add API for set webhook endpointURL

---

linebot/recipient.go
linebot/send_message_test.go

[#230](https://github.com/line/line-bot-sdk-go/issues/230)
[https://developers.line.biz/en/reference/messaging-api/#narrowcast-recipient](https://developers.line.biz/en/reference/messaging-api/#narrowcast-recipient)

Add redelivery object for narrowcast

---

linebot/client.go
linebot/raw.go
linebot/raw_test.go

SDK users can call APIs without waiting for SDK's development(usually, SDK's development is a bit delayed from API release)

Add generic request method. #258

---

linebot/flex.go
linebot/flex_test.go

#234 
3. Use linear gradient as the background image for a box component by setting its background.type property equal to linearGradient.

add background props to BoxComponent

---

README.md
examples/access_token_helper/main.go
examples/delivery_helper/main.go
examples/echo_bot/server.go
examples/echo_bot_handler/server.go
examples/insight_helper/main.go
examples/kitchensink/server.go
examples/richmenu_helper/main.go
go.mod
linebot/example_test.go
linebot/httphandler/httphandler.go
linebot/httphandler/httphandler_test.go

Since PR #264 enabled the go module, it‘s better to follow the [specification of the go module](https://blog.golang.org/v2-go-modules) to upgrade the major version. 
Currently, The latest version of package still stuck at v1.3.0 [pkg.go.dev](https://pkg.go.dev/github.com/line/line-bot-sdk-go/linebot) This change will help the version control back to the major line

upgrade major version to v7 for meets the specification of go module

---

examples/kitchensink/server.go
linebot/client.go
linebot/event.go
linebot/flex_test.go
linebot/get_bot_info.go
linebot/httphandler/httphandler_test.go
linebot/message.go
linebot/oauth.go
linebot/oauth2.go
linebot/raw_test.go
linebot/response.go
linebot/richmenu.go
linebot/send_message_test.go
linebot/webhook.go
linebot/webhook_test.go

See commit.
1. [58ea1fe](https://github.com/line/line-bot-sdk-go/commit/58ea1feff0fef4bbba8bfae97e6370beb54b4f5d) Fix the wrong constant type ⚠️
2. [4e4cc43](https://github.com/line/line-bot-sdk-go/commit/4e4cc4337957f13e749b34751f5a6ece15feb4d6) Typo correction
3. [b89478c](https://github.com/line/line-bot-sdk-go/commit/b89478cc1935ec460f5e43e57fe370e49199f436) Cleanup code
4. [53161b7](https://github.com/line/line-bot-sdk-go/commit/53161b7b7d145995ae87d88ba630217f2b7aa645) Consider nil ⚠️
5. [f670bb4](https://github.com/line/line-bot-sdk-go/commit/f670bb42bf40f10b78c67103ae12e3f94272fe91) Fixed to the correct tag name(`omitemtpy` -> `omitempty`) ⚠️
Typo errors in public names have not been corrected.
I'd like to fix the public name as well ... :(

Fix wrong constant type & other fixes

---

README.md

Replace Travis CI build badge with GitHub Actions build badge.

Update README.md's build badge to GitHub Actions

---

linebot/httphandler/httphandler_test.go
linebot/webhook_test.go

Tests can cause nil pointer dereference if response is `nil` because it
uses `t.Error` that's just report an error to test output. Fixes by
using `t.Fatal` to stop immediately when the `res` is `nil`

Use t.Fatal instead of t.Error on checking nil response

---

linebot/event.go
linebot/webhook_test.go

Fix #295 
- You can now retrieve the text entered by the user in a message sticker
- You can now retrieve up to 1000 user IDs of friends
Reference: https://developers.line.biz/en/news/2021/11/09/messaging-api-update/

Messaging API Update - November 2021 - Support text enter sticker msg.

---

CHANGELOG.md
linebot/version.go

Update version to v7.12.0 for Support Messaging API Update 2021/November, Go 1.17 and bug fix.

Update version to v7.12.0

---

linebot/event.go
linebot/message.go

Fixed PR #298 could not parse enter text "text" from sticker directly.
Original  structure Sticker doesn't have the variable. 
```
type StickerMessage struct {
ID                  string
PackageID           string
StickerID           string
StickerResourceType StickerResourceType
Keywords            []string
quickReplyItems *QuickReplyItems
sender          *Sender
messageType     MessageType
}
```

Fixed #298 sticker text issue, add text parameter.

---

linebot/audience.go
linebot/audience_test.go
linebot/client.go
linebot/response.go

add managing audience api to SDK.
Unit test is not finished.
Ref issue: [Support Audience apis](https://github.com/line/line-bot-sdk-go/issues/194)

add managing audience api

---

linebot/webhook.go

According to https://developers.line.biz/en/reference/messaging-api/#request-headers, It is better to be case-insensitive when handling request headers.

Make the X-Line-Signature header case-insensitive when handling in server side.

---

CHANGELOG.md
linebot/version.go

- Update actions/setup-go action to v4. [\#342](https://github.com/line/line-bot-sdk-go/pull/342)
- Includes `@All` in the mention property of the webhooks. [\#343](https://github.com/line/line-bot-sdk-go/pull/343)([Cheng-Lung Sung](https://github.com/clsung))

Update version to 7.20.0

---

linebot/template_test.go
linebot/template_unmarshal.go

Resolve a task #345 
This is to add `UnmarshalJSON` functionality to `TemplateMessage`.
- `template_unmarshal.go` file and created the `UnmarshalTemplateJSON` method. The logic of this method is almost identical to `UnmarshalFlexMessageJSON` method.
- Add test code to `UnmarshalFlexMessageJSON` (`template_test.go`)
While implementing `UnmarshalTemplateJSON`, I noticed that `UnmarshalJSON` is not implemented for `CarouselColumn` and `ImageCarouselColumn`. However, considering the possibility that it might have a bad influence on other codes, we added `rawColumn` and `rawImageColumn` here and implemented `UnmarshalJSON`. If there is no risk of having a bad influence on other code, modify `CarouselColumn` and `ImageCarouselColumn` to add `UnmarshalJSON`.
There was not enough testing for …

Add unmarshal json for template

---

linebot/webhook.go
linebot/webhook_test.go

i got an error below when consuming TestWebhook endpoint.
`"failed":"linebot: APIError 405 The request method, 'GET', is not supported`
it seems only post method is allowed according to the doc. 
https://developers.line.biz/en/reference/messaging-api/#test-webhook-endpoint

fix: Use POST method for Test Webhook endpoiont

---

linebot/richmenu.go

It seems that the InoutOption of PostbackAction is missing from RichMenuAction.
official doc: https://developers.line.biz/ja/reference/messaging-api/#postback-action
ref: https://github.com/line/line-bot-sdk-go/blob/master/linebot/actions.go#L113
I'm not very experienced, so please let me know if there's anything amiss or if I've overlooked something.

Add InputOption for RichMenuAction

---

.github/workflows/go.yml
README.md
go.mod

I found 1.19 was EOL and 1.21 was released : https://endoflife.date/go

Support Go 1.21 and drop 1.19

---

.github/workflows/release.yml

This change adds github workflow to update `linebot/version.go` forcibly with published git tag when release is published.
If it works, we don't have to update the file manually!
Resolve #362

Update linebot/version.go forcibly when release is published

---

README.md
examples/kitchensink/server.go
generator/src/main/resources/line-bot-sdk-go-generator/api.pebble
linebot/channel_access_token/api_channel_access_token.go
linebot/insight/api_insight.go
linebot/liff/api_liff.go
linebot/manage_audience/api_manage_audience.go
linebot/manage_audience/api_manage_audience_blob.go
linebot/messaging_api/api_messaging_api.go
linebot/messaging_api/api_messaging_api_blob.go
linebot/module/api_line_module.go
linebot/module_attach/api_line_module_attach.go
linebot/shop/api_shop.go

1. This change explains how to get headers and error response in new libraries based on openapi generator.
2. Error message from LINE API is already consumed for error message(`fmt.Errorf(...)`) in SDK. Once error message is consumed, `response.Body` gets empty when we call `~WithHttpInfo` function. This change copies error message to error response again to support (1).

Copy response body on error

---

linebot/get_follower_ids.go
linebot/get_follower_ids_test.go

According to the doc below, the endpoint accepts `limit` query parameter to limit the number of IDs to fetch per one request.
https://developers.line.biz/en/reference/messaging-api/#get-follower-ids
i think it is effective when fetching results by specific chunk size. besides, it can reduce the query cost when it fetches lesser size from the default value.

feat: Add Limit Query Parameter to Get Follower Ids 

---

generator/src/main/resources/line-bot-sdk-go-generator/api.pebble
linebot/channel_access_token/api_channel_access_token.go
linebot/insight/api_insight.go
linebot/manage_audience/api_manage_audience.go
linebot/manage_audience/api_manage_audience_blob.go
linebot/messaging_api/api_messaging_api.go
linebot/messaging_api/tests/handwritten/api_GetFollowers_test.go
linebot/module/api_line_module.go

Currently, `stringify` macro in `api.pebble` doesn't handle `int32` Go type properly. It directly uses `string(...)` to convert `int32` to `string` which will generate a UTF-8 character corresponding to the value of int instead. For example, `string(57)` will result in `"9"` instead of `"57"`. This bug makes `MessagingApiAPI.GetFollowers(start string, limit int32)` to be nearly impossible to use.
To fix this, this PR changes add another condition to `stringify` macro for `Integer` type. With this change, it will use `strconv.FormatInteger(int64(...), 10)` instead of `string(...)` which yield a correct string value.
Apart from the bugfix, I also refactor `api.pebble` a bit to re-use `stringify` macro for any place required to use `string` type. And also add another condition to `stringify` …

bugfix: int32 is converted to incorrect string

---

.github/workflows/generated-code.yml

When we run `generate-code.yml` manually, this doesn't generated code when it's before line-openapi is not updated yet.
This change fixes it. Note line-bot-sdk-php and line-bot-sdk-nodejs do this. (python, java, and go don't do this yet)

Use the latest submodules when generating code is hooked

---

examples/echo_bot/server.go
examples/kitchensink/server.go

While integrating LINE webhook events, I noticed an inconsistency in how errors, specifically ErrInvalidSignature, were being handled. The direct comparison of errors using == does not effectively catch ErrInvalidSignature due to the way Go's error interface works. This led to improper HTTP status codes being returned, affecting the error feedback mechanism.
This PR addresses the issue by updating the error comparison logic in both echo_bot and kitchensink examples. Instead of directly comparing error interfaces, the changes involve comparing the error messages:
In echo_bot/server.go and kitchensink/server.go, modified the conditional checks from if err == linebot.ErrInvalidSignature to if err.Error() == linebot.ErrInvalidSignature.Error(). This ensures that the error comparison is based …

Fix: Correctly handle ErrInvalidSignature comparison

---

.github/workflows/generated-code.yml
.github/workflows/go.yml
.github/workflows/release.yml
README.md
go.mod

1.20 got EOL on 2024-02-06(https://endoflife.date/go)

Support Go 1.22 and drop 1.20

---

.github/workflows/generated-code.yml
.github/workflows/go.yml
.github/workflows/release.yml
README.md
go.mod

Go 1.23.0 is released and 1.21 got EOL.
(https://endoflife.date/go)

Support Go 1.23 and drop 1.21

---

examples/echo_bot_handler/server.go

I found that in the sample code the **function messaging_api.NewMessagingApiAPI** returned error but didn't handle the error immediately.

Fixed handling errors in the wrong place in example

---

generator/src/main/java/line/bot/generator/pebble/IsOmitEmptyFunction.java
linebot/messaging_api/model_limit.go
linebot/messaging_api/model_show_loading_animation_request.go

This resolve https://github.com/line/line-bot-sdk-go/issues/466.
By using the `omitempty` tag on an int field, you can ignore the field during JSON serialization when its value is set to 0. 
This is necessary for endpoints with request bodies that have optional int fields, allowing the request to be made without specifying that field. 
Without the omitempty tag, the request would treat the field as if 0 were explicitly specified.
However, this setting should be limited to fields where specifying a 0 value is not intended. Otherwise, it would prevent the ability to explicitly set a 0 value for those fields.

Fix bug: integer cannot be null

---

generator/src/main/resources/line-bot-sdk-go-generator/api.pebble
linebot/insight/api_insight.go
linebot/manage_audience/api_manage_audience.go
linebot/messaging_api/api_messaging_api.go
linebot/module/api_line_module.go

This resolves https://github.com/line/line-bot-sdk-go/issues/474.
We are customizing SDK code generation to generate code that directly passes arguments to functions, instead of using a request body struct for the API.
As a result, we are unable to use the "omitempty" tag to ignore fields with empty strings.
To address this issue, we will modify the code to exclude optional string fields from url.Values when they are empty.

Ignore empty string for query parameter

---

generator/src/main/resources/line-bot-sdk-go-generator/api.pebble
linebot/channel_access_token/api_channel_access_token.go
linebot/module_attach/api_line_module_attach.go

This resolves https://github.com/line/line-bot-sdk-go/issues/464 ~~with PR https://github.com/line/line-openapi/pull/70~~
We are customizing SDK code generation to generate code that directly passes arguments to functions, instead of using a request body struct for the API.
As a result, we are unable to use the "omitempty" tag to ignore fields with empty strings.
To address this issue, we will modify the code to exclude optional string fields from url.Values when they are empty.

Ignore empty string for optional args

---

.github/workflows/generated-code.yml
linebot/messaging_api/model_app_type_demographic.go

When some code are changed by modifying code generator or templates, forgetting to commit the expected changes can lead to mistakes. I want to enforce that the PR author commits the generated code, by causing the CI to fail if the generated code is not committed. This PR achieves that.

PR must fail when generated code is not committed

---

.github/workflows/generated-code.yml

I've found CI always fails when renovate updates git submodule...
If there is un-committed changes by renovate PR(= new code will be generated by openapi generator), I think we can allow this. Finally github actions open PR after the PR by renovate is merged.
Another way is to make renovate to run script to generate code again, but the cost is a little bit high.(https://docs.renovatebot.com/configuration-options/#postupgradetasks) 
The situation won't get bad even when we merge this change, so let me merge this change.

Allow renovate PR to have un committed changes

---

linebot/channel_access_token/tests/handwritten/api_IssueStatelessChannelToken_test.go
linebot/messaging_api/tests/handwritten/api_GetMembersIds_test.go
linebot/messaging_api/tests/handwritten/model_limit_test.go

This PR adds tests for these changes to correctly ignore empty values.
- https://github.com/line/line-bot-sdk-go/pull/496
- https://github.com/line/line-bot-sdk-go/pull/497
- https://github.com/line/line-bot-sdk-go/pull/498

Add tests for ignore-empty series

---

.github/workflows/check-eol-newrelease.yml
.github/workflows/close-issue.yml
.github/workflows/create-draft-release.yml
.github/workflows/generate-code.yml
.github/workflows/go.yml
renovate.json5

To avoid supply chain attacks, specify actions in GitHub Actions workflows using commit hashes instead of version numbers. Pinact-action will fail the CI job if this is not done. Renovate already supports updates in the commit hash state, so there is no issue.
- https://github.com/suzuki-shunsuke/pinact-action
- does pinact-action verify the checksum of the version of aqua it is using? Yes!: 
- https://github.com/suzuki-shunsuke/pinact
- line/line-bot-sdk-python https://github.com/line/line-bot-sdk-python/pull/772
- line/line-bot-sdk-php https://github.com/line/line-bot-sdk-php/pull/680
- line/line-bot-sdk-nodejs https://github.com/line/line-bot-sdk-nodejs/pull/1201
- line/line-bot-sdk-java https://github.com/line/line-bot-sdk-java/pull/1576
- line/line-bot-sdk-go …

Pin commit hash of github actions to avoid supply chain attacks

---

.github/workflows/generate-code.yml
.github/workflows/go.yml

To re-enable the merge queue, this change adds merge_group to several jobs.
original: https://github.com/line/line-bot-sdk-java/pull/1592

Require more jobs in merge queue

---

.github/workflows/generate-code.yml

`.github/workflows/generate-code.yml` creates another PR when the submitted PR has diff ... 😄 
This change fixes it.

Do not create another auto PR when a job runs for PR

---

.github/workflows/generate-code.yml
.github/workflows/go.yml

`actions/setup-go` provides aliases for active 2 Go versions. With this, we don't have to maintain go version for github actions workflows like https://github.com/line/line-bot-sdk-go/pull/471/files and https://github.com/line/line-bot-sdk-go/pull/578/files.
reference: https://github.com/actions/setup-go/blob/d35c59abb061a4a6fb18e82ac0862c26744d6ab5/README.md?plain=1#L134-L161

Use stable and oldstable instead actual version for actions/setup-go

---

generator/src/main/resources/line-bot-sdk-go-generator/api.pebble

This PR addresses a modification to the generator responsible for producing the Go SDK from OpenAPI definitions. Specifically, it introduces support for query parameters that include arrays.
Enhanced the generator to handle array-type query parameters.
Here is an example of how such an API call might look in a shell script:
```sh
curl -X GET "https://api.line.me/v2/bot/example?param=value1&param=value2"
```
Currently, there are no endpoints that utilize such parameters. However, this update is a preparatory step for future API enhancements.

Fix pebble for array-type query parameter

---

.github/ISSUE_TEMPLATE/question.md
CONTRIBUTING.md

Same as https://github.com/line/line-bot-sdk-php/pull/715

Update CONTRIBUTING.md to enhance development guidelines
