line/line-bot-sdk-go

linebot/event.go
linebot/webhook_test.go

ref. https://github.com/line/line-bot-sdk-go/issues/14
It does not break compatibility.

implements Marshaler to Event

---

examples/echo_bot/server.go

`PushMessage` can't be used in Free Plan.

Replace `PushMessate` to `ReplyMessage` in example code

---

examples/echo_bot_handler/server.go
examples/echo_bot_handler/server_appengine.go

I forgot event type decision.
Maybe, These codes will panic without it when received beacon etc events.

fix example codes

---

README.md
examples/echo_bot/server.go

These are some suggestions for the documentation for this SDK. Please take a look and review the changes. If there are any issues, please let me know. Thanks!

Fix documentation issues

---

linebot/get_profile_test.go
linebot/response.go

fix typo of `PictureURL`

---

README.md

Add some content to "How to Start"

Add "How to Start" Section into README.md

---

linebot/client.go
linebot/send_message.go
linebot/send_message_test.go

Support multicast API

---

linebot/send_message_test.go
linebot/template.go

- follow https://devdocs.line.me/en/#template-messages

Add `datetime picker` template action

---

linebot/client.go
linebot/get_profile.go
linebot/get_profile_test.go

https://devdocs.line.me/en/#get-group-room-member-profile

Add group/room member profile API

---

examples/kitchensink/server.go

Added:
- Reply datetime picker
- Reply image carousel

Update kitchensink example 

---

linebot/client.go
linebot/example_test.go
linebot/get_content.go
linebot/get_ids.go
linebot/get_ids_test.go
linebot/get_profile.go
linebot/response.go

Close #55 
https://devdocs.line.me/en/#get-group-room-member-ids

Add group/room member IDs API

---

examples/richmenu_helper/main.go
linebot/client.go
linebot/response.go
linebot/richmenu.go
linebot/richmenu_test.go

- add richmenu api
- add helper in examples/
- tested via  examples/richmenu_helper
- implement #61

Add `Richmenu API`

---

linebot/message.go

sorry.
I forget to use a variable.

use var MessageTypeFlex for set type flexMessage

---

examples/kitchensink/server.go
linebot/event.go
linebot/message.go
linebot/webhook_test.go

resolve #82.
- Add `FileMessage` type
- Remove `json.Marshaler` from `Message` interface

Add `FileMessage` type

---

linebot/client.go
linebot/liff.go
linebot/response.go

Please code review my liff api, and merge to master.
Thanks.

#issue-liff add liff api

---

linebot/client.go
linebot/liff.go
linebot/liff_test.go
linebot/response.go
linebot/richmenu_test.go

- Add `liff_test.go`
- Fix `liff.go`
- Remove unnecessary comments

Update around LIFF API

---

.reviewdog.yml
.travis.yml

Try `golint` and `go vet` in `travis.yml` because reviewdog often fails...

Retire reviewdog and update travis.yml

---

examples/richmenu_helper/main.go
linebot/client.go
linebot/richmenu.go
linebot/richmenu_test.go

Note: added Test() functions are compiled into the package only when running go test

Add default rich menu API.

---

.travis.yml

https://blog.golang.org/go1.12

Support Go 1.12

---

linebot/event.go

Tweak event.go

---

examples/richmenu_helper/main.go
linebot/client.go
linebot/response.go
linebot/richmenu.go
linebot/richmenu_test.go

- add isSuccuss(2xx) for checkResponse
- implement #139

Richmenu for multiple user

---

examples/delivery_helper/main.go
linebot/client.go
linebot/delivery.go
linebot/delivery_test.go
linebot/response.go

- implment GetNumberReplyMessages(), GetNumberPushMessages(), GetNumberMulticastMessages()
- add example

Add functions for #120: get number of messages

---

.travis.yml
README.md
script/codecov.sh

Close #93
https://codecov.io/gh/line/line-bot-sdk-go
https://github.com/codecov/example-go#caveat-multiple-files

Use CodeCov

---

linebot/client.go
linebot/get_quota.go
linebot/get_quota_test.go
linebot/response.go

Add get message quota support

---

linebot/send_message_test.go

Fix testing #151

---

linebot/event.go
linebot/webhook_test.go

A stay event was added to beacon event

---

linebot/event.go
linebot/webhook_test.go

Add `mode` property to API webhook event

---

linebot/message.go
linebot/send_message_test.go
linebot/sender.go

Ref: https://developers.line.biz/en/reference/messaging-api/#icon-nickname-switch

Add sender property to Message objects.

---

linebot/get_profile_test.go
linebot/response.go

To implement get user's language in GetProfile API.
Fixed https://github.com/line/line-bot-sdk-go/issues/200

Fix #200 Implement for Get user's language.

---

linebot/event.go
linebot/webhook_test.go

Ref: https://developers.line.biz/en/news/2020/03/30/per-sticker-text-type-added/

New sticker resource type "PER_STICKER_TEXT"

---

linebot/flex.go

Add `Style` `Decoration` Field of TextComponent #205  https://developers.line.biz/en/reference/messaging-api/#f-text

Add Latest Field of `TextComponent` #205

---

linebot/emoji.go
linebot/event.go
linebot/message.go
linebot/webhook_test.go

- implements one feature request of #207

webhook has emoji now (#207)

---

linebot/flex.go

BoxComponent Add
- Width
- Height
- CornerRadius
- BackgroundColor
- BorderColor

Update BoxComponent Properties

---

CHANGELOG.md
linebot/version.go

Update version to v7.5.0 for 2020 May and June updated.

Update version to v7.5.0.

---

linebot/event.go
linebot/webhook_test.go

* Unsend event has been added
* Video viewing complete event has been added

Aug api update: unsend/video viewing complete

---

linebot/send_message.go
linebot/send_message_test.go

To add upToRemainingQuota API for narrowCast limit.
Fixed #226.

FIX #226: Add upToRemainingQuota

---

linebot/flex.go
linebot/flex_test.go

update https://github.com/line/line-bot-sdk-go/issues/234
https://developers.line.biz/en/reference/messaging-api/#span

Support message api span component in flex message

---

linebot/client.go
linebot/response.go
linebot/webhook.go
linebot/webhook_test.go

for #233 
Update Messaging API October 2020
https://developers.line.biz/en/news/2020/10/06/messaging-api-update-october-2020/
2020/https://developers.line.biz/en/reference/messaging-api/#test-webhook-endpoint

Add API TestWebhook() 

---

CHANGELOG.md
linebot/version.go

Update version to v7.7.0 for 2020 October update.

Update version to v7.7.0

---

linebot/flex.go
linebot/flex_test.go
linebot/flex_unmarshal.go

fixes [issue#174 ](https://github.com/line/line-bot-sdk-go/issues/174)
[add action props of box component  and maxLines props of text component](https://developers.line.biz/en/news/2018/08/06/actions-label-update/)

Add action props of box component  and maxLines props of text component

---

linebot/event.go
linebot/message.go
linebot/webhook_test.go

Add keywords property to Sticker event

---

linebot/send_message_test.go
linebot/template.go

#211 
Add default action to button template and carousel template

add default action to button template and carousel template

---

linebot/event.go
linebot/mention.go
linebot/message.go
linebot/webhook_test.go

#247 [Text message type properties to support user-mention](https://developers.line.biz/en/reference/messaging-api/#wh-text)

Add mention props for text message

---

linebot/progress_test.go
linebot/response.go

#247 [Get narrowcast message status properties to know acceptedTime and completedTime](https://developers.line.biz/en/reference/messaging-api/#get-narrowcast-progress-status)

add acceptedTime and completedTime to MessagesProgressResponse

---

CHANGELOG.md
linebot/version.go

Update version to v7.8.0 for 2020 December and 2021 January update.

Update version to v7.8.0

---

linebot/flex.go
linebot/flex_test.go

`hero` can set `box` or `image` type.
https://developers.line.biz/ja/reference/messaging-api/#bubble

support multiple type to hero

---

linebot/flex.go
linebot/flex_test.go

#234 
▼ Implements
2. Added support for animated images
5. Box component has justifyContent and alignItems property
7. Allowed text to automatically shrink to fit a component's width

Flex Message Update 2 - 1

---

linebot/richmenu.go
linebot/richmenu_test.go

follow the doc below
https://developers.line.biz/en/reference/messaging-api/#postback-action
set `DisplayText` and `Label` to `RichmenuAction` if need.

support postback type fields in richmenu action

---

linebot/client.go
linebot/get_follower_ids.go
linebot/get_follower_ids_test.go
linebot/get_ids_test.go
linebot/response.go

Add get-follower-ids-api

---

CHANGELOG.md
linebot/version.go

Update version to v7.9.0 for 2021 March update and Support Flex Message Update 2.

Update version to v7.9.0

---

CHANGELOG.md
linebot/version.go

Update version to v7.9.1 to fix issue after enable go modules

Update version to v7.9.1

---

linebot/response.go
linebot/webhook_test.go

use boolean for Active in WebhookInfoResponse

---

linebot/flex.go
linebot/flex_test.go

helped #272 
add test case.
@kkdai 
FYI: https://github.com/line/line-bot-sdk-go/pull/272#pullrequestreview-631020398

Add test case for #272

---

linebot/client.go
linebot/response.go
linebot/richmenu.go
linebot/richmenu_test.go

Ref: https://developers.line.biz/en/news/2021/06/21/switch-between-multiple-rich-menus/

Add rich menu alias function calls

---

linebot/message.go
linebot/message_test.go

Implement #251, add Message.Type()

---

CHANGELOG.md
linebot/version.go

Update version to v7.10.0 for Messaging API June update and bug fix.

Update version to v7.10.0

---

examples/richmenu_helper/main.go
linebot/event.go
linebot/richmenu.go
linebot/webhook_test.go

Fix #285 Support rich menu switch action

---

CHANGELOG.md
linebot/version.go

Update version to v7.10.1 for Bug fix and README updated.

Update version to v7.10.1

---

linebot/flex.go
linebot/flex_test.go

I need to use border in box component but It missing border width, so I add border width for box component and update test case

add border width for box component

---

CHANGELOG.md
linebot/version.go

Update version to v7.12.1 for Sticker text bug fix.

Update version to v7.12.1

---

CHANGELOG.md
linebot/version.go

Update version to 7.13.0,  Add support for Audience Managing API

Update version to v7.13.0

---

linebot/flex.go
linebot/flex_test.go
linebot/flex_unmarshal.go

#305 
- Add `FlexVideoAspectRatioType` for some common video aspect ratios (and the inverse ones) 
- Add `VideoComponent` which is also a `FlexComponent`

Support VideoComponent in Flex message

---

linebot/flex.go
linebot/flex_test.go

#305 
- Support `maxWidth` and `maxHeight` in `BoxComponent`
- Support `lineSpacing` in `TextComponent`

Support Flex Message Update v3

---

linebot/event.go
linebot/get_ids_test.go
linebot/raw.go
linebot/webhook_test.go

#310 
- Add webhookEventId property
- Add deliveryContext property

add webhook redelivery

---

CHANGELOG.md
linebot/version.go

Update version to 7.15.0 - add webhook redelivery

Update version to 7.15.0

---

CHANGELOG.md
linebot/version.go

Update version to 7.16.0 - Support automatic opening and closing of the rich menu when tapping a rich menu.

Update version to 7.16.0

---

linebot/client.go
linebot/richmenu.go
linebot/richmenu_test.go

add ValidateRichMenuObjectMethod

---

CHANGELOG.md
linebot/version.go

Update version 7.17.0 - Add support for the endpoint for validating rich menu objects.

Update version to 7.17.0

---

CHANGELOG.md
linebot/version.go

Update version 7.18.0 - Add support for validating message objects APIs.

Update version to 7.18.0

---

linebot/liff.go
linebot/liff_test.go

- remote ViewRequest
- API change, add/update liff should call LIFFApp{} instead of View{}
- fixes #335

Add liffApp properties

---

linebot/client.go
linebot/oauth.go
linebot/oauth_test.go
linebot/response.go

adding new method based on issue here https://github.com/line/line-bot-sdk-go/issues/337. please help to review @kkdai

feat(method): verify access token method

---

CHANGELOG.md
linebot/version.go

Update version to 7.19.0

---

linebot/mention.go
linebot/webhook_test.go

- add MentionedTargetType
- fixes #341

Includes @All in the mention property of the webhooks

---

README.md

Minimal contribution, but I noticed that there was a small typo in the README.md file.

Fixed a small typo README.md

---

.github/workflows/generated-code.yml

I guess 1.20 is evaluated as 1.2 ...

Fix go version written in workflow to generate code

---

.github/release.yml

same as https://github.com/line/line-bot-sdk-java/blob/master/.github/release.yml

Import release.yml to generate release note automatically based on label

---

generator/src/main/resources/line-bot-sdk-go-generator/api.pebble
linebot/channel_access_token/api_channel_access_token.go
linebot/insight/api_insight.go
linebot/liff/api_liff.go
linebot/manage_audience/api_manage_audience.go
linebot/manage_audience/api_manage_audience_blob.go
linebot/messaging_api/api_messaging_api.go
linebot/messaging_api/api_messaging_api_blob.go
linebot/messaging_api/tests/handwritten/calling_api_twice.go
linebot/messaging_api/tests/handwritten/calling_api_twice_test.go
linebot/module/api_line_module.go
linebot/module_attach/api_line_module_attach.go
linebot/shop/api_shop.go

Fix https://github.com/line/line-bot-sdk-go/issues/396

Modify endpoint URL generation in Url function

---

.github/workflows/generated-code.yml

There is a test in the CI that checks for differences between the automatically generated files from OpenAPI. However, if this test fails, it doesn't indicate which files have differences. I will modify the CI to output this information.

Show filenames of diff from auto-generated files in CI
